### ISSUE TITLE
How fast is it to do the reconstruction ? 

### ISSUE THREAD

**Issue by Jiakui** [IVRL/VolRecon#1]
Dear author,

After training on a large dataset, given a couple of images around an object, how soon can I use the pretrained weights to obtain the 3d mesh ?  

Thanks!

**Comment by FangjinhuaWang** [comment]
Hi,

As discussed in our paper, it takes about 30 seconds to render a depth map and RGB image with size as 800x600. The tsdf fusion is fast and only takes several seconds.
