### ISSUE TITLE
Visualization results

### ISSUE THREAD

**Issue by Shubhendu-Jena** [IVRL/VolRecon#10]
Hi, thanks for your amazing work. In the results section of the paper, a comparison with other methods such as sparseneus and mvsnerf has been done. I wanted to enquire about the results for mvsnerf and how you acquired them. I tried running marching cubes mvsnerf with a density threshold of 10 and am not getting satisfactory results. If possible, I'd be also grateful if you would be willing to share the code to do the same.

Thank you in advance

**Comment by FangjinhuaWang** [comment]
Hi. For the results for MVSNeRF, IBRNet, we actually borrow the results from SparseNeuS paper. So maybe you can directly ask the authors of SparseNeuS. To be honest, I think choosing the threshold is quite tricky.

**Comment by Shubhendu-Jena** [comment]
Hi, thank you so much for the quick response. I understand, I'll try and ask the authors of sparseneus.
