### ISSUE TITLE
Is there a little mistake on confusing SRDF and SDF in Appendix 7 of the paper?

### ISSUE THREAD

**Issue by kianyale** [IVRL/VolRecon#12]
Hi, thanks for your great work!
When I read the paper, I find it seems that there is a mistake in Appendix 7. 
![QQ图片20231030171718](https://github.com/IVRL/VolRecon/assets/108654290/db2b99f9-36ef-4f32-9f4d-3199ee67f279)

By the way, I wonder if there exists an algorithm to construct SRDF from depth images.
Thanks a lot~

**Comment by ryf1123** [comment]
Hello, sorry for the late reply. 

This is a toy example that the world only consists of two surfaces. In this setup, the SRDF value of any point _x_ on the ray is the same as SDF value when the surface is perpendicular to the ray. In both cases, the absolute values of SDF or SRDF are the distance along the ray. 

Hope my explaination answers your question and feel free to re-open this issue.
