### ISSUE TITLE
Question about the quantitative evaluation results on DTU dataset

### ISSUE THREAD

**Issue by prstrive** [IVRL/VolRecon#13]
Thanks for publishing this great work! But we just found that there are something mismatches between our reproduction results and your paper. We adopt your released checkpoint to generate the mesh and test the chamfer distance of two image sets. We can only get the 1.48 average scores of these two sets (1.38 for the first set and 1.58 for the second set), and the results depicted in your paper is 1.38. So is this result reasonable? and the results in your paper is the result of the first set? or are we misunderstanding something?

**Comment by FangjinhuaWang** [comment]
Hi. I am not sure why there is difference in evaluation. we have reproduced the results before open source.
