### ISSUE TITLE
Reproduce problem regarding the edge of the picture and generated mesh

### ISSUE THREAD

**Issue by RenieWell** [IVRL/VolRecon#14]
Thanks for sharing the great work!
When I was tried to reproduce your work, I found there is some blurring in the edge of the prediction image like following:
![image](https://github.com/IVRL/VolRecon/assets/4987555/d3e8ef41-3304-4531-949b-43b0769187fc)
This image is generated by using the checkpoint you provided in the github.
And when I  used the checkpoint trained with the DTU dataset by the bash script script/train_dtu.sh I still got the blurring images predicitons.
![image](https://github.com/IVRL/VolRecon/assets/4987555/3324a04c-3362-42e8-8d68-a5e069653956)
And I observed some inconsistency in the mesh (inconsistency betwent the checkpoint you provided in the github and the checkpoint after trained locally).
![image](https://github.com/IVRL/VolRecon/assets/4987555/da38008a-dec4-42a4-85d8-f693939dfc71)
The left mesh is generated by the checkpoint you provided in the github, and the right one is generated by the model I trained locally.

Right now, I am confused with if there is some problems with my environment?
Or there will be some difference when running the code for several times?

**Comment by FangjinhuaWang** [comment]
Hi, we also have such blur at edges. This is because the input images are too sparse. In our case, the training is quite stable and converges fast. there is no explicit difference between multiple trainings.

**Comment by RenieWell** [comment]
> Hi, we also have such blur at edges. This is because the input images are too sparse. In our case, the training is quite stable and converges fast. there is no explicit difference between multiple trainings.

Thanks for the information.
Then, I will check the training part of my code.
