### ISSUE TITLE
Why is there a difference between the VolRecon and SparseNeus when computing "iter_cos" from "true_cos" in renderer.py?

### ISSUE THREAD

**Issue by kianyale** [IVRL/VolRecon#15]
Hi, thanks for your great work!
I understand why __true_cos__ in your implementaion is $-1$ because of SRDF.
ButI notice that, in your implementation, __iter_cos__ in $renderer.py$ equals $1.5\cdot$__true_cos__ when __cos_anneal_ratio__ is equal to $1$, but $\cdot 1.5$ exceeds the upper bound of the cos function, which is different from implementation between NeuS and SparseNeus. I wonder if there are some reasons why you designed this.
Looking forward to your reply!

Note: 
In VolRecon: 
~~~python
iter_cos = -(-true_cos * 0.5 + 0.5 * (1.0 - cos_anneal_ratio) - true_cos * cos_anneal_ratio)
~~~
In SparseNeus & NeuS:
~~~python
iter_cos = -(F.relu(-true_cos * 0.5 + 0.5) * (1.0 - cos_anneal_ratio) + F.relu(-true_cos) * cos_anneal_ratio)
~~~

**Comment by FangjinhuaWang** [comment]
Hi, thanks for pointing this out! this looks like a bug. we will look into that. you can use the code from NeuS.
