### ISSUE TITLE
Quantitative results

### ISSUE THREAD

**Issue by 05063112lcs** [IVRL/VolRecon#19]
Hello, thank you very much for your excellent work, I recently reproduced your results, but there were a series of problems during the data test, I wonder if you can provide some solutions. 

![image](https://github.com/IVRL/VolRecon/assets/149451618/8ced93f8-cd7e-4a19-91e8-67b9a8678f56)
       When I tested with the test set you provided, none of the metrics here were shown, and I would like to know what is causing this. Also, I'd like to know if the quantitative analysis results in your article were taken from the visual interface or from the code

**Comment by xiaoyu20010808** [comment]
hi, i also meet this question , do you have save it ?

**Comment by 05063112lcs** [comment]
Problems with the dataset, re-download the dataset



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 19, 2024 17:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IVRL/VolRecon] Quantitative results (Issue #19)




 
hi, i also meet this question , do you have save it ?

**Comment by xiaoyu20010808** [comment]
ok, thank you for your reply!

**Comment by xiaoyu20010808** [comment]
Hello, I have downloaded the test data set provided by the author for several times, but the visual result is 0 every time during verification. Do you also download the test data set provided by the author? Are there any other changes?

**Comment by ryf1123** [comment]
> Hello, I have downloaded the test data set provided by the author for several times, but the visual result is 0 every time during verification. Do you also download the test data set provided by the author? Are there any other changes?

Hi, as I did not see this issue, I am not sure why this is happening. For debugging, one simple thing to try could be setting a break point or add `print(psnr_coarse)` before this [line](https://github.com/IVRL/VolRecon/blob/main/code/model.py#L251), to see if it true that all the samples give 0 metric.

**Comment by xiaoyu20010808** [comment]
> > 您好，我已经多次下载了笔者提供的测试数据集，但是每次验证时视觉结果都是 0。您是否还下载了作者提供的测试数据集？还有其他变化吗？
> 
> 嗨，因为我没有看到这个问题，所以我不确定为什么会这样。对于调试，可以尝试的一件简单事情是设置一个断点或在此[行](https://github.com/IVRL/VolRecon/blob/main/code/model.py#L251)之前添加，以查看所有样本是否都给出 0 度量。`print(psnr_coarse)`

hihi, i print  psnr_coarse, and the output is 0

**Comment by xiaoyu20010808** [comment]
> > Hello, I have downloaded the test data set provided by the author for several times, but the visual result is 0 every time during verification. Do you also download the test data set provided by the author? Are there any other changes?
> 
> Hi, as I did not see this issue, I am not sure why this is happening. For debugging, one simple thing to try could be setting a break point or add `print(psnr_coarse)` before this [line](https://github.com/IVRL/VolRecon/blob/main/code/model.py#L251), to see if it true that all the samples give 0 metric.

 hello, thank for your reply, i find that you set psnr/corse, psnr/fine to 0 in model.py line 274,Does this cause the indicator to be 0 during the test.

**Comment by ryf1123** [comment]
Hi, thanks for update; then maybe you can try to print the psnr before this [line](https://github.com/IVRL/VolRecon/blob/main/code/model.py#L326); one possibility might be `piq.psnr` is not working normally.
