### ISSUE TITLE
depth_fusion

### ISSUE THREAD

**Issue by ShanWang-Shan** [IVRL/VolRecon#3]
Thank you for your outstanding job. I have a question regarding the depth fusion and depth evaluation source code. Will you be releasing this code in the future? 

I noticed that there is a depth_fusion.sh file, but I could not find the depth_fusion.py file. Could you please let me know where I can find the related source code? Additionally, it would be wonderful if you could provide a link to the depth evaluation source code as well.

Thank you in advance.

**Comment by FangjinhuaWang** [comment]
Hi, the depth fusion is from multi-view stereo methods. For example, you can have a look [here](https://github.com/FangjinhuaWang/IterMVS/blob/afb870c2d3e15b15e15f244f8d6822c4acb207d5/eval.py#L212)

**Comment by ShanWang-Shan** [comment]
Thank you!
