### ISSUE TITLE
Single view reconstruction

### ISSUE THREAD

**Issue by fzy139** [IVRL/VolRecon#6]
Hi,

Thanks for your excellent work. 

I'm curious about reconstructing objects with single input view, like pixelNeRF. I know it's a highly ill-posed problem but I still wonder the performance in this setting (I noticed the ablation about source views in the appendix that show the result of 2 views at least). 

Or any suggestions on how to improve the performance, such as fine tuning under single view setting?

**Comment by FangjinhuaWang** [comment]
Hi, our method is more similar to ibrnet and mvsnerf, which needs multiple views.
