### ISSUE TITLE
how calculate camera parameter ?

### ISSUE THREAD

**Issue by goometasoft** [IVRL/VolRecon#9]
how calculate camera parameter ?

**Comment by ryf1123** [comment]
Hi, for training and evaluation, you can use the camera provided in the DTU dataset: https://github.com/IVRL/VolRecon?tab=readme-ov-file#reproducing-sparse-view-reconstruction-on-dtu. For custom dataset, you can use COLMAP to estimate camera parameter given a set of images. More details could be found: https://github.com/IVRL/VolRecon?tab=readme-ov-file#evaluation-on-custom-dataset
